appName: checkoutservice
appImage: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/checkoutservice
appVersion: v0.10.6
appReplicas: 2
containerPort: 5050
containerEnvVars:
  PORT: "5050"
  CART_SERVICE_ADDR: "cartservice:7070"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  EMAIL_SERVICE_ADDR: "emailservice:8080"
  PAYMENT_SERVICE_ADDR: "paymentservice:50051"

servicePort: 5050