
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJS0w4UHdqb3hRL3d3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBNE1qY3dNalE0TXpCYUZ3MHpOakE0TWpRd01qVXpNekJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNYY1ZyVTNWYWJyTGhLeWQ1d3EzeGVZcjNaMG9CSFAxSXIyR2pIN096enEvQi85aXYxYkxzWFdsWUkKcHR2NTRUK25ndi85VTRtKzVxYjVaUzY1Vk5NMGxOeGt5b29MM2xKR01qSWJaZm52dlJNYUxoVjk0OWVXb3VORQpNN0lJRTZpc3JJZUpWaUx4K0gvUGlRUHdyQXBNcWxMa0lXVUJBWHpWUDB5OEhUVWNnNXZRRUhYQVF0b0VmdStuCnBkT3NsS1kvSXRYbXl1K0xiVE5OMEs5N1dPRm91S2ZRMW83WVBtWHRwci83cGExR0dpNmJ4ZHh3ekswYWIxV08KMnZ0OWhoOHBVejNMMjQrZWpFc2UrbCs3UE5PbkdOTlVvdU95OERFd1E4RndlOWl4eEx5UHFiTUxxUGRmU285Lwp2TERRMnMwZGRaOVY4K1ROR3BiRkJET2VCS2NCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRa2tJbHFyN1p3OFBnVGZ4QzRIeFZzU1J5bEhUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ08wcHg0dm1YbwozTDZSTkxVNHE4QmFySW53K2FUV2lwRWZkLzFNSXlXZk1OWkdETXhKWjNqK3F2S2ttZElLQ2dsQjRJNStDVXF1CnVrS09LdERUY2IxYVIxSXd4M3NVQS9hSDc2WHBpdWNYa1Q2ZE9TdCtlUHVVbzJySzEzQ1dUZjdnbytiN0tnRXkKTU9HSXl1QjgzQ2Zlbi9oMm1oS3JtdUpRTk5DTEZEeUJsTFRoUTlGelk3Rzc0ckEvMEp5UjAySGt3dlBnTXl1OQpxOUgzQlUrTUxMTTB6WTBaSHNFUW1mdUFKVUU5Y3RJVXorc2EzV2NnV1AzamNjNnRqbGo0d3Jqd1EyMnFWdmN3CmJrMldEQ3d1ZTNnempjQ0VxMGVad2k3a2t4VW9UOUtkRW8wZUxMNFhaNGZITTlXQS9IZ3VHZElzblk5V1UxWmQKeEJQcjBRZVlJQlUvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://a09434fc-2692-4069-bc44-be176864e3e6.ap-southeast-1-gw.linodelke.net:443
  name: lke648265

users:
- name: lke648265-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImhsNjRPS05qZmdidlFTMm9TbzNGbGEyUXBDeTJ2NkZrN1AtajZDRzA4NUkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tbWt2dnQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMTEzYTI1MWUtNzBjNC00YWY2LWIzZjAtZWM0ZmIyYTNiMzc0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.Ml1HhgdUh959ljoCY4z6okE-sqqUFLMiA5DXCqkHZ3UjnucXy0w4ducGAmU_J3SkGUNRAwRABqLTvRoMDEudtasyxRtKsMKeFo2QF9lgkMS3l44aUa-HfNXKybxkwFB-sBN_vcOA-1FxmATupzzBVqR8mS4zgeOjuhlh3Lg2vcfhSQbI03FUHFMhEF46-P-4ZEi4-97pFIpB1uS0brpwyVf9aYiC8Z47iZDEFHKBQ7Kj2w4b6Q5nhf15FDIbi3MHv7uIsb2dqCeQtD3t5DjlFuMWrP9aQga-nllZukhiymexPKlPSGGttMJZBxfLpN7TRUj8RaWD00A-hEVzVsPiig

contexts:
- context:
    cluster: lke648265
    namespace: default
    user: lke648265-admin
  name: lke648265-ctx

current-context: lke648265-ctx
